"""
SRISHTI·AI — Mock Subsurface & Drilling Database
Calibrated for Upper Assam Basin (Oil India Limited & ONGC operations)

Data Sources / Calibration References:
  - Kumar & Talreja (2018), AAPG Search & Discovery #42308: Mud weight windows for Baghjan J-bend wells
  - Alam, Chatterjee & Dasgupta (2019), Geophys. J. Int. 216(1): Pore pressure & stress magnitudes, Upper Assam
  - Dasgupta et al. (2019), J. Petrol. Geol. 42(3): Barail overpressure at 3,700–4,100m
  - CAG Report No. 42 of 2015: OIL drilling performance benchmarks
  - NGT Katakey Committee Report (2020): Baghjan-5 blowout investigation

NOTE: All data is synthetic / mock. Real OIL operational data is proprietary.
      Values are calibrated to published ranges but do not represent any actual well.
"""

# ─────────────────────────────────────────────────────────────────────
# 1. WELLS DATABASE  (18 wells across 7 fields)
# ─────────────────────────────────────────────────────────────────────

WELLS_DB = [
    # ── Moran Field (OIL) ──────────────────────────────────────────
    {
        "id": "MOR-29",
        "name": "MORAN-29",
        "field": "Moran",
        "block": "MOR-III",
        "lat": 27.4853,
        "lon": 95.3456,
        "spud_date": "2026-08-15",
        "td_depth_md": 2418.0,
        "target_depth_md": 3500.0,
        "status": "ACTIVE DRILLING",
        "rig": "OIL-RIG-04",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 6.8,
        "active_hazard_distance_m": 32.0,
        "primary_hazard": "Approaching Barail Gas Kick Precursor Horizon (2,450m)",
        "total_npt_hrs": 18.0,
        "mud_weight_ppg": 10.8,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2200.0
    },
    {
        "id": "MOR-07",
        "name": "MORAN-7",
        "field": "Moran",
        "block": "MOR-I",
        "lat": 27.4912,
        "lon": 95.3398,
        "spud_date": "2018-03-10",
        "td_depth_md": 3450.0,
        "target_depth_md": 3450.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-01",
        "well_type": "Exploration",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Differential Sticking in Girujan Clay (1,680m)",
        "total_npt_hrs": 336.0,
        "mud_weight_ppg": 10.9,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2100.0
    },
    {
        "id": "MOR-12",
        "name": "MORAN-12",
        "field": "Moran",
        "block": "MOR-II",
        "lat": 27.4789,
        "lon": 95.3521,
        "spud_date": "2021-11-04",
        "td_depth_md": 3520.0,
        "target_depth_md": 3520.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-03",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Mud Losses in Tipam Sandstone TS-3 (2,480m)",
        "total_npt_hrs": 88.0,
        "mud_weight_ppg": 10.4,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2150.0
    },
    {
        "id": "MOR-56",
        "name": "MORAN-56",
        "field": "Moran",
        "block": "MOR-III",
        "lat": 27.4830,
        "lon": 95.3510,
        "spud_date": "2024-06-20",
        "td_depth_md": 2890.0,
        "target_depth_md": 3400.0,
        "status": "SUSPENDED",
        "rig": "OIL-RIG-06",
        "well_type": "Development",
        "current_formation": "Tipam Sandstone",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Tight hole / pack-off in Namsang gravel (1,120m)",
        "total_npt_hrs": 72.0,
        "mud_weight_ppg": 10.2,
        "bit_size": '12-1/4"',
        "casing_shoe_md": 1500.0
    },

    # ── Nahorkatiya Field (OIL) ────────────────────────────────────
    {
        "id": "NHK-162",
        "name": "NAHORKATIYA-162",
        "field": "Nahorkatiya",
        "block": "NHK-Main",
        "lat": 27.2845,
        "lon": 95.3567,
        "spud_date": "2019-07-22",
        "td_depth_md": 3650.0,
        "target_depth_md": 3650.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-07",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Lost Circulation in Tipam Sandstone TS-3 (2,540m)",
        "total_npt_hrs": 114.0,
        "mud_weight_ppg": 10.4,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2200.0
    },
    {
        "id": "NHK-342",
        "name": "NAHORKATIYA-342",
        "field": "Nahorkatiya",
        "block": "NHK-South",
        "lat": 27.2711,
        "lon": 95.3644,
        "spud_date": "2023-01-15",
        "td_depth_md": 3420.0,
        "target_depth_md": 3420.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-05",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Barail coal caving / packoff (3,150m)",
        "total_npt_hrs": 46.0,
        "mud_weight_ppg": 11.0,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2250.0
    },
    {
        "id": "NHK-561",
        "name": "NAHORKATIYA-561",
        "field": "Nahorkatiya",
        "block": "NHK-East",
        "lat": 27.2920,
        "lon": 95.3780,
        "spud_date": "2026-05-10",
        "td_depth_md": 3100.0,
        "target_depth_md": 3800.0,
        "status": "ACTIVE DRILLING",
        "rig": "OIL-RIG-08",
        "well_type": "Exploration",
        "current_formation": "Barail Group",
        "current_rop": 5.2,
        "active_hazard_distance_m": 600.0,
        "primary_hazard": "Approaching Kopili overpressure zone (3,700m)",
        "total_npt_hrs": 24.0,
        "mud_weight_ppg": 10.6,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2300.0
    },
    {
        "id": "NHK-656",
        "name": "NAHORKATIYA-656",
        "field": "Nahorkatiya",
        "block": "NHK-Main",
        "lat": 27.2880,
        "lon": 95.3620,
        "spud_date": "2022-09-05",
        "td_depth_md": 3850.0,
        "target_depth_md": 3850.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-07",
        "well_type": "Exploration",
        "current_formation": "Kopili Formation",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Kopili borehole breakout at 3,780m (narrow MW window)",
        "total_npt_hrs": 168.0,
        "mud_weight_ppg": 10.8,
        "bit_size": '6"',
        "casing_shoe_md": 3100.0
    },

    # ── Baghjan Field (OIL) ────────────────────────────────────────
    {
        "id": "BGH-05",
        "name": "BAGHJAN-5",
        "field": "Baghjan",
        "block": "BGH-Ext",
        "lat": 27.6012,
        "lon": 95.4215,
        "spud_date": "2006-02-18",
        "td_depth_md": 3870.0,
        "target_depth_md": 3870.0,
        "status": "CRITICAL INCIDENT",
        "rig": "OIL-RIG-09",
        "well_type": "Exploration",
        "current_formation": "Lakadong / Therria",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Blowout (May 2020) — Premature BOP removal during workover on Langpar formation",
        "total_npt_hrs": 4560.0,
        "mud_weight_ppg": 12.8,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 3100.0
    },
    {
        "id": "BGH-09",
        "name": "BAGHJAN-9",
        "field": "Baghjan",
        "block": "BGH-Ext",
        "lat": 27.5980,
        "lon": 95.4180,
        "spud_date": "2017-11-25",
        "td_depth_md": 3720.0,
        "target_depth_md": 3720.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-10",
        "well_type": "Development",
        "current_formation": "Kopili Formation",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Gas kick in lower Barail at 3,380m (pit gain 18 bbl)",
        "total_npt_hrs": 192.0,
        "mud_weight_ppg": 11.2,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 3050.0
    },
    {
        "id": "BGH-21",
        "name": "BAGHJAN-21",
        "field": "Baghjan",
        "block": "BGH-Main",
        "lat": 27.5950,
        "lon": 95.4250,
        "spud_date": "2024-03-08",
        "td_depth_md": 4100.0,
        "target_depth_md": 4100.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-11",
        "well_type": "Exploration",
        "current_formation": "Sylhet Limestone",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Kopili overpressure (MW spike to 12.3 ppg at 3,850m)",
        "total_npt_hrs": 240.0,
        "mud_weight_ppg": 12.3,
        "bit_size": '6"',
        "casing_shoe_md": 3650.0
    },

    # ── Duliajan / Hugrijan (OIL HQ) ──────────────────────────────
    {
        "id": "DLJ-101",
        "name": "DULIAJAN-101",
        "field": "Duliajan",
        "block": "HQ-Central",
        "lat": 27.3712,
        "lon": 95.3045,
        "spud_date": "2025-09-10",
        "td_depth_md": 3250.0,
        "target_depth_md": 3250.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-04",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Shallow gravel washouts in Alluvium (0–280m)",
        "total_npt_hrs": 18.0,
        "mud_weight_ppg": 10.0,
        "bit_size": '12-1/4"',
        "casing_shoe_md": 2100.0
    },
    {
        "id": "HGJ-48",
        "name": "HUGRIJAN-48",
        "field": "Hugrijan",
        "block": "HGJ-North",
        "lat": 27.3560,
        "lon": 95.3210,
        "spud_date": "2020-04-15",
        "td_depth_md": 3380.0,
        "target_depth_md": 3380.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-02",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Tipam thief zone lost circulation (2,450m–2,600m)",
        "total_npt_hrs": 96.0,
        "mud_weight_ppg": 10.3,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2150.0
    },

    # ── Lakwa Field (ONGC Assam Asset) ─────────────────────────────
    {
        "id": "LK-112",
        "name": "LAKWA-112",
        "field": "Lakwa",
        "block": "LK-Central",
        "lat": 26.9320,
        "lon": 94.8850,
        "spud_date": "2016-08-12",
        "td_depth_md": 3600.0,
        "target_depth_md": 3600.0,
        "status": "COMPLETED",
        "rig": "ONGC-RIG-15",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Barail gas influx (3,220m) — pit gain 12 bbl",
        "total_npt_hrs": 144.0,
        "mud_weight_ppg": 11.0,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2250.0
    },
    {
        "id": "LK-245",
        "name": "LAKWA-245",
        "field": "Lakwa",
        "block": "LK-South",
        "lat": 26.9180,
        "lon": 94.8920,
        "spud_date": "2021-02-28",
        "td_depth_md": 3150.0,
        "target_depth_md": 3150.0,
        "status": "COMPLETED",
        "rig": "ONGC-RIG-18",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Girujan clay swelling / bit balling (1,850m)",
        "total_npt_hrs": 56.0,
        "mud_weight_ppg": 10.5,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2100.0
    },

    # ── Rudrasagar Field (ONGC Assam Asset) ────────────────────────
    {
        "id": "RDS-25",
        "name": "RUDRASAGAR-25",
        "field": "Rudrasagar",
        "block": "RDS-Main",
        "lat": 26.9710,
        "lon": 94.9350,
        "spud_date": "2015-05-20",
        "td_depth_md": 3400.0,
        "target_depth_md": 3400.0,
        "status": "COMPLETED",
        "rig": "ONGC-RIG-12",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Stuck pipe in Girujan Clay (1,720m) — 8 days fishing",
        "total_npt_hrs": 192.0,
        "mud_weight_ppg": 10.6,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2050.0
    },
    {
        "id": "RDS-147",
        "name": "RUDRASAGAR-147",
        "field": "Rudrasagar",
        "block": "RDS-East",
        "lat": 26.9680,
        "lon": 94.9420,
        "spud_date": "2014-10-10",
        "td_depth_md": 3350.0,
        "target_depth_md": 3350.0,
        "status": "CRITICAL INCIDENT",
        "rig": "ONGC-RIG-14",
        "well_type": "Development",
        "current_formation": "Barail Group",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Uncontrolled gas leak during workover (June 2025)",
        "total_npt_hrs": 720.0,
        "mud_weight_ppg": 11.4,
        "bit_size": '8-1/2"',
        "casing_shoe_md": 2200.0
    },

    # ── Digboi Field (Historical) ──────────────────────────────────
    {
        "id": "DGB-1001",
        "name": "DIGBOI-1001",
        "field": "Digboi",
        "block": "DGB-Anticline",
        "lat": 27.3930,
        "lon": 95.6180,
        "spud_date": "2010-06-15",
        "td_depth_md": 2200.0,
        "target_depth_md": 2200.0,
        "status": "COMPLETED",
        "rig": "OIL-RIG-02",
        "well_type": "Development",
        "current_formation": "Tipam Sandstone",
        "current_rop": 0.0,
        "active_hazard_distance_m": 0.0,
        "primary_hazard": "Shallow gas pockets in Dihing Formation (180m)",
        "total_npt_hrs": 12.0,
        "mud_weight_ppg": 9.8,
        "bit_size": '12-1/4"',
        "casing_shoe_md": 800.0
    },
]


# ─────────────────────────────────────────────────────────────────────
# 2. FORMATIONS DATABASE  (11 formations — real Upper Assam stratigraphy)
#
# Depth ranges represent the Central Shelf (Nahorkatiya–Moran–Baghjan trend).
# ROP ranges calibrated from CAG Report No. 42 of 2015.
# MW windows from Kumar & Talreja (2018, AAPG #42308) and Dasgupta et al. (2019).
# ─────────────────────────────────────────────────────────────────────

FORMATIONS_DB = [
    {
        "id": "FMN-01",
        "name": "Alluvium / Dihing",
        "canonical_name": "Alluvium / Dihing",
        "group_name": "Holocene–Pleistocene",
        "lithology": "Unconsolidated sands, gravels, clays, silt; freshwater aquifer zone",
        "depth_top_md": 0,
        "depth_bottom_md": 300,
        "top_md_m": 0,
        "base_md_m": 300,
        "avg_rop": 25.0,
        "rop_range": "15–35 m/hr",
        "drill_time_days": 3.5,
        "npt_hrs": 12,
        "primary_hazard": "Washouts & Shallow Gas Pockets",
        "recommended_mw_ppg": "8.6–9.0",
        "pore_pressure_ppg": 8.42,
        "fracture_gradient_ppg": 12.0,
        "color": "#65A30D"
    },
    {
        "id": "FMN-02",
        "name": "Dhekiajuli",
        "canonical_name": "Dhekiajuli",
        "group_name": "Pliocene–Pleistocene",
        "lithology": "Coarse sands, grit, pebble beds; freshwater protection zone",
        "depth_top_md": 300,
        "depth_bottom_md": 800,
        "top_md_m": 300,
        "base_md_m": 800,
        "avg_rop": 22.0,
        "rop_range": "15–30 m/hr",
        "drill_time_days": 6.5,
        "npt_hrs": 24,
        "primary_hazard": "Borehole Instability & Lost Circulation",
        "recommended_mw_ppg": "8.8–9.2",
        "pore_pressure_ppg": 8.42,
        "fracture_gradient_ppg": 12.5,
        "color": "#D97706"
    },
    {
        "id": "FMN-03",
        "name": "Namsang",
        "canonical_name": "Namsang",
        "group_name": "Mio-Pliocene",
        "lithology": "Sandstones, grits, conglomerate lenses; regional unconformity at base",
        "depth_top_md": 800,
        "depth_bottom_md": 1500,
        "top_md_m": 800,
        "base_md_m": 1500,
        "avg_rop": 18.0,
        "rop_range": "12–25 m/hr",
        "drill_time_days": 10.0,
        "npt_hrs": 36,
        "primary_hazard": "Lost Circulation in Gravel Zones",
        "recommended_mw_ppg": "9.0–9.4",
        "pore_pressure_ppg": 8.42,
        "fracture_gradient_ppg": 13.0,
        "color": "#EA580C"
    },
    {
        "id": "FMN-04",
        "name": "Girujan Clay",
        "canonical_name": "Girujan Clay",
        "group_name": "Tipam Group (Cap Rock)",
        "lithology": "Mottled clays, bluish-green mudstones; highly reactive montmorillonite swelling clays",
        "depth_top_md": 1500,
        "depth_bottom_md": 2200,
        "top_md_m": 1500,
        "base_md_m": 2200,
        "avg_rop": 12.0,
        "rop_range": "8–18 m/hr",
        "drill_time_days": 16.0,
        "npt_hrs": 180,
        "primary_hazard": "Differential Sticking, Severe Clay Swelling & Bit Balling",
        "recommended_mw_ppg": "9.35–9.75",
        "pore_pressure_ppg": 8.42,
        "fracture_gradient_ppg": 14.0,
        "color": "#C2410C"
    },
    {
        "id": "FMN-05",
        "name": "Tipam Sandstone",
        "canonical_name": "Tipam Sandstone",
        "group_name": "Tipam Group (Pay Zone)",
        "lithology": "Thick multi-storied braided channel sandstones (TS-1 to TS-6) with shale stringers",
        "depth_top_md": 2200,
        "depth_bottom_md": 3000,
        "top_md_m": 2200,
        "base_md_m": 3000,
        "avg_rop": 8.0,
        "rop_range": "5–12 m/hr",
        "drill_time_days": 14.0,
        "npt_hrs": 120,
        "primary_hazard": "Lost Circulation (Thief Zones in TS-3 & TS-5) & Bit Gauge Wear",
        "recommended_mw_ppg": "9.8–10.6",
        "pore_pressure_ppg": 8.55,
        "fracture_gradient_ppg": 14.5,
        "color": "#E0A96D"
    },
    {
        "id": "FMN-06",
        "name": "Bokabil / Surma",
        "canonical_name": "Bokabil / Surma",
        "group_name": "Surma Group",
        "lithology": "Claystones and thin sandstones; often thin or pinched out on shelf highs",
        "depth_top_md": 3000,
        "depth_bottom_md": 3100,
        "top_md_m": 3000,
        "base_md_m": 3100,
        "avg_rop": 7.0,
        "rop_range": "5–10 m/hr",
        "drill_time_days": 4.0,
        "npt_hrs": 8,
        "primary_hazard": "Local Seal Transition — Minor Cavings",
        "recommended_mw_ppg": "10.0–10.4",
        "pore_pressure_ppg": 8.60,
        "fracture_gradient_ppg": 14.8,
        "color": "#6B7280"
    },
    {
        "id": "FMN-07",
        "name": "Barail Group",
        "canonical_name": "Barail Group",
        "group_name": "Late Eocene–Early Oligocene",
        "lithology": "Interbedded fine-medium sandstones, carbonaceous shales & thick coal seams (Tikak Parbat)",
        "depth_top_md": 3100,
        "depth_bottom_md": 3700,
        "top_md_m": 3100,
        "base_md_m": 3700,
        "avg_rop": 5.5,
        "rop_range": "3–8 m/hr",
        "drill_time_days": 22.0,
        "npt_hrs": 280,
        "primary_hazard": "High-Pressure Gas Kicks, Coal Caving & Packoffs, Overpressured Compartments",
        "recommended_mw_ppg": "10.2–11.5",
        "pore_pressure_ppg": 9.35,
        "fracture_gradient_ppg": 15.0,
        "color": "#475569"
    },
    {
        "id": "FMN-08",
        "name": "Kopili Formation",
        "canonical_name": "Kopili Formation",
        "group_name": "Jaintia Group (Late Eocene)",
        "lithology": "Dark grey fossiliferous marine shales with thin calcareous sandstones; geomechanically unstable",
        "depth_top_md": 3700,
        "depth_bottom_md": 4000,
        "top_md_m": 3700,
        "base_md_m": 4000,
        "avg_rop": 3.5,
        "rop_range": "2–6 m/hr",
        "drill_time_days": 18.0,
        "npt_hrs": 220,
        "primary_hazard": "Narrow MW Window (10.15–10.8 ppg), Borehole Breakouts, Reactive Shales",
        "recommended_mw_ppg": "10.15–10.8",
        "pore_pressure_ppg": 9.90,
        "fracture_gradient_ppg": 13.8,
        "color": "#7C3AED"
    },
    {
        "id": "FMN-09",
        "name": "Sylhet Limestone",
        "canonical_name": "Sylhet Limestone",
        "group_name": "Jaintia Group (Middle Eocene)",
        "lithology": "Nummulitic dense shelf limestone, calcareous shales, dolomitic streaks",
        "depth_top_md": 4000,
        "depth_bottom_md": 4200,
        "top_md_m": 4000,
        "base_md_m": 4200,
        "avg_rop": 3.0,
        "rop_range": "2–5 m/hr",
        "drill_time_days": 12.0,
        "npt_hrs": 48,
        "primary_hazard": "Hard Dense Carbonates — Severe Bit Wear",
        "recommended_mw_ppg": "9.5–10.2",
        "pore_pressure_ppg": 9.10,
        "fracture_gradient_ppg": 15.5,
        "color": "#0891B2"
    },
    {
        "id": "FMN-10",
        "name": "Lakadong / Therria",
        "canonical_name": "Lakadong / Therria",
        "group_name": "Jaintia Group (Paleocene–Early Eocene)",
        "lithology": "Calcareous sandstones, basal clastics, quartzitic sands; high-pressure gas/condensate reservoir",
        "depth_top_md": 4200,
        "depth_bottom_md": 4500,
        "top_md_m": 4200,
        "base_md_m": 4500,
        "avg_rop": 2.5,
        "rop_range": "2–5 m/hr",
        "drill_time_days": 15.0,
        "npt_hrs": 96,
        "primary_hazard": "Deep High-Pressure Gas/Condensate — Severe Overpressure",
        "recommended_mw_ppg": "11.0–12.3",
        "pore_pressure_ppg": 11.0,
        "fracture_gradient_ppg": 14.0,
        "color": "#DC2626"
    },
    {
        "id": "FMN-11",
        "name": "Pre-Cambrian Basement",
        "canonical_name": "Pre-Cambrian Basement",
        "group_name": "Archean–Proterozoic",
        "lithology": "Granite, granodiorite, gneissic complex",
        "depth_top_md": 4500,
        "depth_bottom_md": 6000,
        "top_md_m": 4500,
        "base_md_m": 6000,
        "avg_rop": 1.0,
        "rop_range": "0.5–2 m/hr",
        "drill_time_days": 8.0,
        "npt_hrs": 36,
        "primary_hazard": "Extreme Bit Wear & Low ROP — PDC bit failure",
        "recommended_mw_ppg": "9.0–9.5",
        "pore_pressure_ppg": 8.42,
        "fracture_gradient_ppg": 16.0,
        "color": "#334155"
    },
]


# ─────────────────────────────────────────────────────────────────────
# 3. DRILLING EVENTS DATABASE  (15 events)
# ─────────────────────────────────────────────────────────────────────

DRILLING_EVENTS_DB = [
    # EVT-01: Differential sticking — MOR-07 in Girujan Clay
    {
        "id": "EVT-01",
        "well_id": "MOR-07",
        "event_type": "Stuck Pipe",
        "formation": "Girujan Clay",
        "formation_id": "FMN-04",
        "depth_md": 1680.0,
        "depth_from_md_m": 1680.0,
        "depth_to_md_m": 1680.0,
        "severity": "HIGH",
        "npt_cost_inr": 80000000.0,
        "duration_hrs": 336.0,
        "description": "Differential pipe sticking across sticky montmorillonite clay after 3 hours stationary drill string during directional survey. Overpull exceeded 110,000 lbs. Mud weight was 10.9 ppg with excessive filter cake (8/32\").",
        "mitigation": "Spotted 50 bbl OBM lubricant soak pill weighted to 11.0 ppg with 4% pipe-release surfactant. Soak time 12 hrs. String jarred free. Total NPT: 14 days incl. fishing. Recommendation: maintain >60 RPM rotation in Girujan, never allow stationary string >5 min.",
        "source_doc": "WCR_Moran_7_2018.pdf",
        "source_page": 147,
        "reviewer_status": "APPROVED",
        "verified_by": "P. Saikia (Chief Drilling Eng., OIL)"
    },
    # EVT-02: Lost circulation — NHK-162 in Tipam TS-3
    {
        "id": "EVT-02",
        "well_id": "NHK-162",
        "event_type": "Lost Circulation",
        "formation": "Tipam Sandstone",
        "formation_id": "FMN-05",
        "depth_md": 2540.0,
        "depth_from_md_m": 2540.0,
        "depth_to_md_m": 2580.0,
        "severity": "MEDIUM",
        "npt_cost_inr": 15000000.0,
        "duration_hrs": 48.0,
        "description": "Sudden loss of returns (60 bbl/hr) upon penetrating micro-fractured porous Tipam sandstone TS-3 interval. Active pit volume dropped by 38 bbl.",
        "mitigation": "Pulled off bottom to 2,500m. Spotted 25 bbl coarse CaCO3 (30 ppb) + medium Mica (15 ppb) LCM pill. Squeezed at 250 psi annular pressure. Reduced MW from 11.2 to 10.4 ppg. Full circulation restored. Recommendation: maintain MW within 10.2–10.6 ppg window in Tipam TS-3.",
        "source_doc": "WCR_Naharkatiya_162.pdf",
        "source_page": 82,
        "reviewer_status": "APPROVED",
        "verified_by": "B. Borah (Lead Mud Eng., OIL)"
    },
    # EVT-03: Gas kick — BGH-05 in Barail Group (pre-blowout incident)
    {
        "id": "EVT-03",
        "well_id": "BGH-05",
        "event_type": "Gas Kick",
        "formation": "Barail Group",
        "formation_id": "FMN-07",
        "depth_md": 3380.0,
        "depth_from_md_m": 3380.0,
        "depth_to_md_m": 3400.0,
        "severity": "CRITICAL",
        "npt_cost_inr": 450000000.0,
        "duration_hrs": 720.0,
        "description": "Unpredicted pore pressure surge in Barail carbonaceous coal-shale sequence. Pit volume gained 22 bbl in 4 minutes. Standpipe pressure flutter +180 psi. Background gas jumped from 25 to 340 units.",
        "mitigation": "Shut in well via annular BOP per OISD-STD-174. Circulated out kick using Wait & Weight method with 12.8 ppg kill mud. Total well control event duration: 30 days including kill verification and cement squeeze.",
        "source_doc": "IncidentReport_BGH5_2020.pdf",
        "source_page": 14,
        "reviewer_status": "APPROVED",
        "verified_by": "R. Gogoi (Safety Supervisor, OIL)"
    },
    # EVT-04: Differential sticking — MOR-29 in Girujan Clay (current well)
    {
        "id": "EVT-04",
        "well_id": "MOR-29",
        "event_type": "Differential Sticking",
        "formation": "Girujan Clay",
        "formation_id": "FMN-04",
        "depth_md": 1720.0,
        "depth_from_md_m": 1720.0,
        "depth_to_md_m": 1720.0,
        "severity": "MEDIUM",
        "npt_cost_inr": 3500000.0,
        "duration_hrs": 6.0,
        "description": "Drill string dragged heavily during connection at 1,720m in Girujan Clay. Immediate spotting of lubricant pill prevented severe sticking.",
        "mitigation": "Spotted OBM lubricant pill, maintained rotation at 60 RPM, successfully freed in 6 hours. Adjusted MW from 10.5 to 10.8 ppg for the remaining Girujan interval.",
        "source_doc": "DDR_MOR29_Day14.pdf",
        "source_page": 2,
        "reviewer_status": "APPROVED",
        "verified_by": "K. Sarma (Company Man)"
    },
    # EVT-05: Baghjan-5 Blowout (real documented event)
    {
        "id": "EVT-05",
        "well_id": "BGH-05",
        "event_type": "Blowout",
        "formation": "Lakadong / Therria",
        "formation_id": "FMN-10",
        "depth_md": 3870.0,
        "depth_from_md_m": 3729.0,
        "depth_to_md_m": 3872.0,
        "severity": "CRITICAL",
        "npt_cost_inr": 25000000000.0,
        "duration_hrs": 4560.0,
        "description": "Well kicked and blew out on 27-May-2020 during workover to recomplete from Langpar (3,870m) to Lakadong/Therria (3,729–3,739m). Root cause: premature BOP removal before establishing adequate mechanical barriers. Single cement plug placed at shallow ~1,000m in deviated section instead of above production packer (~3,700m). Gas ignited on 9-Jun-2020. Well killed by snubbing unit (Alert Disaster Control, Singapore) on 15-Nov-2020. Permanently P&A on 3-Dec-2020 (190 days).",
        "mitigation": "Specialized snubbing unit mobilized from Alert Disaster Control (Singapore) and Schlumberger. Heavy kill mud pumped via snubbing string. Well permanently plugged and abandoned. NGT Katakey Committee: ensure BOP is never removed without verified dual mechanical barriers.",
        "source_doc": "NGT_Katakey_Committee_BGH5_2020.pdf",
        "source_page": 1,
        "reviewer_status": "APPROVED",
        "verified_by": "NGT Committee / DGMS Investigation"
    },
    # EVT-06: Lost circulation — MOR-12 in Tipam
    {
        "id": "EVT-06",
        "well_id": "MOR-12",
        "event_type": "Lost Circulation",
        "formation": "Tipam Sandstone",
        "formation_id": "FMN-05",
        "depth_md": 2480.0,
        "depth_from_md_m": 2480.0,
        "depth_to_md_m": 2520.0,
        "severity": "MEDIUM",
        "npt_cost_inr": 12000000.0,
        "duration_hrs": 36.0,
        "description": "Partial loss of returns (40 bbl/hr) in Tipam TS-3 thief zone. Similar loss pattern to NHK-162 event in same stratigraphic interval.",
        "mitigation": "Spotted 20 bbl coarse CaCO3 + mica LCM pill. Reduced MW to 10.4 ppg. Losses stopped after 2 pills. Drilled ahead with maintained 10.4 ppg to Tipam base.",
        "source_doc": "DDR_MOR12_Day42.pdf",
        "source_page": 3,
        "reviewer_status": "APPROVED",
        "verified_by": "B. Borah (Lead Mud Eng., OIL)"
    },
    # EVT-07: Gas kick — BGH-09 in lower Barail
    {
        "id": "EVT-07",
        "well_id": "BGH-09",
        "event_type": "Gas Kick",
        "formation": "Barail Group",
        "formation_id": "FMN-07",
        "depth_md": 3380.0,
        "depth_from_md_m": 3380.0,
        "depth_to_md_m": 3400.0,
        "severity": "HIGH",
        "npt_cost_inr": 85000000.0,
        "duration_hrs": 192.0,
        "description": "Gas influx at 3,380m in lower Barail coal-shale sequence. Pit gain 18 bbl. SPP increased by 140 psi. Connection gas rose to 280 units.",
        "mitigation": "Shut in on annular BOP per OISD-STD-174. Wait & Weight kill with 11.2 ppg mud. Kill verification over 3 circulations. Total event: 8 days. Casing shoe integrity confirmed with LOT.",
        "source_doc": "WCR_Baghjan_9.pdf",
        "source_page": 98,
        "reviewer_status": "APPROVED",
        "verified_by": "R. Gogoi (Safety Supervisor, OIL)"
    },
    # EVT-08: Coal caving — NHK-342 in Barail
    {
        "id": "EVT-08",
        "well_id": "NHK-342",
        "event_type": "Coal Caving / Packoff",
        "formation": "Barail Group",
        "formation_id": "FMN-07",
        "depth_md": 3150.0,
        "depth_from_md_m": 3150.0,
        "depth_to_md_m": 3180.0,
        "severity": "MEDIUM",
        "npt_cost_inr": 8000000.0,
        "duration_hrs": 46.0,
        "description": "Severe coal cavings from Tikak Parbat coal seams at 3,150–3,180m. Annulus packed off during POOH. Torque spikes to 22,000 ft-lbs.",
        "mitigation": "Circulated clean with high-vis sweeps (30 bbl each, 3 sweeps). Increased MW to 11.0 ppg for better borehole stability. Wiper trips every 50m drilled. Recommendation: maintain inhibitive KCl-polymer mud system in Barail coal intervals.",
        "source_doc": "WCR_Naharkatiya_342.pdf",
        "source_page": 65,
        "reviewer_status": "APPROVED",
        "verified_by": "A. Hazarika (Drilling Supt, OIL)"
    },
    # EVT-09: Borehole breakout — NHK-656 in Kopili
    {
        "id": "EVT-09",
        "well_id": "NHK-656",
        "event_type": "Borehole Breakout",
        "formation": "Kopili Formation",
        "formation_id": "FMN-08",
        "depth_md": 3780.0,
        "depth_from_md_m": 3780.0,
        "depth_to_md_m": 3820.0,
        "severity": "HIGH",
        "npt_cost_inr": 45000000.0,
        "duration_hrs": 168.0,
        "description": "Severe borehole breakout and cavings in Kopili reactive shales at 3,780m. Hole enlarged from 8.5\" to 14\". Caliper log confirmed 65% hole enlargement. Narrow MW window (10.15–10.8 ppg) with pore pressure at 9.9 ppg.",
        "mitigation": "Increased MW to 10.8 ppg (approaching fracture gradient at 13.8 ppg). Ran cement squeeze to stabilize worst intervals. Set 7\" liner from 3,100m to 3,820m. Recommendation: set 9-5/8\" casing shoe deep into Kopili per Kumar & Talreja (2018) geomech study.",
        "source_doc": "WCR_Naharkatiya_656.pdf",
        "source_page": 112,
        "reviewer_status": "APPROVED",
        "verified_by": "S. Das (Geomechanics Lead, Schlumberger)"
    },
    # EVT-10: Kopili overpressure — BGH-21
    {
        "id": "EVT-10",
        "well_id": "BGH-21",
        "event_type": "Overpressure Kick",
        "formation": "Kopili Formation",
        "formation_id": "FMN-08",
        "depth_md": 3850.0,
        "depth_from_md_m": 3850.0,
        "depth_to_md_m": 3880.0,
        "severity": "HIGH",
        "npt_cost_inr": 65000000.0,
        "duration_hrs": 240.0,
        "description": "Severe pore pressure ramp crossing into Kopili Formation. Pore pressure rose from 63 pcf to 74 pcf (8.42 to 9.9 ppg) as predicted by Dasgupta et al. (2019). Pit gain 15 bbl. MW had to be increased from 10.4 to 12.3 ppg.",
        "mitigation": "Shut in per OISD-STD-174. Killed with 12.3 ppg weighted mud. Set 7\" liner at 3,650m shoe before resuming. Total NPT: 10 days. Lesson: mandatory pre-drill geomechanical model for any Kopili penetration.",
        "source_doc": "WCR_Baghjan_21.pdf",
        "source_page": 88,
        "reviewer_status": "APPROVED",
        "verified_by": "P. Saikia (Chief Drilling Eng., OIL)"
    },
    # EVT-11: Barail gas influx — LK-112
    {
        "id": "EVT-11",
        "well_id": "LK-112",
        "event_type": "Gas Kick",
        "formation": "Barail Group",
        "formation_id": "FMN-07",
        "depth_md": 3220.0,
        "depth_from_md_m": 3220.0,
        "depth_to_md_m": 3240.0,
        "severity": "HIGH",
        "npt_cost_inr": 55000000.0,
        "duration_hrs": 144.0,
        "description": "Gas influx at 3,220m in Barail sandstone-coal transition. Pit gain 12 bbl over 8 minutes. Background gas surged from 15 to 220 units. SPP flutter +120 psi.",
        "mitigation": "Shut in per ONGC SOP. Driller's Method kill with 11.0 ppg mud. Gas circulated out over 2 bottoms-up. Kill verified over 24 hrs static observation.",
        "source_doc": "WCR_Lakwa_112.pdf",
        "source_page": 75,
        "reviewer_status": "APPROVED",
        "verified_by": "M. Baruah (Well Control Specialist, ONGC)"
    },
    # EVT-12: Stuck pipe — RDS-25 in Girujan Clay
    {
        "id": "EVT-12",
        "well_id": "RDS-25",
        "event_type": "Stuck Pipe",
        "formation": "Girujan Clay",
        "formation_id": "FMN-04",
        "depth_md": 1720.0,
        "depth_from_md_m": 1720.0,
        "depth_to_md_m": 1720.0,
        "severity": "HIGH",
        "npt_cost_inr": 42000000.0,
        "duration_hrs": 192.0,
        "description": "Differential sticking at 1,720m in Girujan Clay during pipe connection. String stationary for 8 minutes due to equipment malfunction. Overpull 95,000 lbs could not free string.",
        "mitigation": "Spotted 40 bbl OBM soak pill with surfactant. Jarred for 3 days without success. Back-off attempted at 1,710m. Sidetracked with whipstock at 1,680m. Total fishing + sidetrack: 8 days. Lesson learned: never exceed 5 min stationary time in Girujan.",
        "source_doc": "WCR_Rudrasagar_25.pdf",
        "source_page": 134,
        "reviewer_status": "APPROVED",
        "verified_by": "D. Kalita (Drilling Supt, ONGC Assam)"
    },
    # EVT-13: Girujan bit balling — LK-245
    {
        "id": "EVT-13",
        "well_id": "LK-245",
        "event_type": "Bit Balling",
        "formation": "Girujan Clay",
        "formation_id": "FMN-04",
        "depth_md": 1850.0,
        "depth_from_md_m": 1830.0,
        "depth_to_md_m": 1870.0,
        "severity": "LOW",
        "npt_cost_inr": 5000000.0,
        "duration_hrs": 56.0,
        "description": "Severe bit balling in reactive Girujan clay at 1,850m. ROP dropped from 12 m/hr to 1.5 m/hr. PDC bit cutters completely packed with clay. Torque erratic between 8,000 and 18,000 ft-lbs.",
        "mitigation": "POOH to change bit. Ran polycrystalline insert bit with anti-balling coating. Added 5% KCl to mud system for clay inhibition. ROP recovered to 10 m/hr.",
        "source_doc": "DDR_Lakwa_245_Day18.pdf",
        "source_page": 2,
        "reviewer_status": "APPROVED",
        "verified_by": "M. Baruah (Well Control Specialist, ONGC)"
    },
    # EVT-14: Shallow gas — DGB-1001
    {
        "id": "EVT-14",
        "well_id": "DGB-1001",
        "event_type": "Shallow Gas",
        "formation": "Alluvium / Dihing",
        "formation_id": "FMN-01",
        "depth_md": 180.0,
        "depth_from_md_m": 180.0,
        "depth_to_md_m": 195.0,
        "severity": "MEDIUM",
        "npt_cost_inr": 2000000.0,
        "duration_hrs": 12.0,
        "description": "Shallow gas pocket encountered at 180m in Dihing Formation gravels. Mud returns became gas-cut (gas units spiked to 450). Minor flow observed at wellhead.",
        "mitigation": "Increased pump rate to circulate out gas. Raised MW from 9.5 to 9.8 ppg. Gas dissipated after 3 bottoms-up circulations. Conductor set at 200m with cement to surface.",
        "source_doc": "DDR_Digboi_1001_Day3.pdf",
        "source_page": 1,
        "reviewer_status": "APPROVED",
        "verified_by": "N. Phukan (Rig Manager, OIL)"
    },
    # EVT-15: Tipam thief zone — HGJ-48
    {
        "id": "EVT-15",
        "well_id": "HGJ-48",
        "event_type": "Lost Circulation",
        "formation": "Tipam Sandstone",
        "formation_id": "FMN-05",
        "depth_md": 2520.0,
        "depth_from_md_m": 2450.0,
        "depth_to_md_m": 2600.0,
        "severity": "MEDIUM",
        "npt_cost_inr": 18000000.0,
        "duration_hrs": 96.0,
        "description": "Progressive seepage losses escalating to 45 bbl/hr across Tipam TS-3 to TS-5 interval (2,450–2,600m). Three LCM pills required before losses were controlled.",
        "mitigation": "Pill 1: 25 bbl coarse CaCO3. Reduced losses to 20 bbl/hr. Pill 2: 30 bbl CaCO3 + mica + cellophane flakes. Reduced to 5 bbl/hr. Pill 3: 20 bbl fine-medium CaCO3 sealer. Full returns restored. Reduced MW from 10.6 to 10.3 ppg.",
        "source_doc": "WCR_Hugrijan_48.pdf",
        "source_page": 58,
        "reviewer_status": "APPROVED",
        "verified_by": "B. Borah (Lead Mud Eng., OIL)"
    },
]


# ─────────────────────────────────────────────────────────────────────
# 4. DOCUMENTS DATABASE  (12 documents)
# ─────────────────────────────────────────────────────────────────────

DOCUMENTS_DB = [
    {
        "id": "DOC-001",
        "filename": "WCR_Moran_7_2018.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "MOR-07",
        "pages": 312,
        "status": "COMPLETED",
        "confidence": 94.8,
        "entities_count": 482,
        "processing_time_s": 248,
        "raw_excerpt": "SECTION 8: OPERATIONAL INCIDENTS (Page 147)\nDATE: 04-MAY-2018 | DEPTH: 1,680m MD | FORMATION: Girujan Clay\nDifferential pipe sticking across sticky montmorillonite clay. Spotted 50 bbl OBM lubricant pill. Jarred free after 14 days.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "P. Saikia (Chief Drilling Eng.)"
    },
    {
        "id": "DOC-002",
        "filename": "WCR_Naharkatiya_162.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "NHK-162",
        "pages": 245,
        "status": "COMPLETED",
        "confidence": 96.2,
        "entities_count": 390,
        "processing_time_s": 192,
        "raw_excerpt": "DDR Summary: Severe lost circulation at 2,540m MD in Tipam Sandstone TS-3. Spotted 25 bbl coarse CaCO3 pill with mica. Reduced MW to 10.4 ppg. Full returns restored.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "B. Borah (Lead Mud Eng.)"
    },
    {
        "id": "DOC-003",
        "filename": "DDR_MOR29_Day14.pdf",
        "doc_type": "Daily Drilling Report",
        "well_id": "MOR-29",
        "pages": 4,
        "status": "COMPLETED",
        "confidence": 98.4,
        "entities_count": 42,
        "processing_time_s": 14,
        "raw_excerpt": "Day 14: Drilled from 1,680m to 1,740m. Sticking observed at 1,720m in Girujan Clay. Spotted OBM pill, freed in 6 hrs. Rotation maintained at 60 RPM.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "K. Sarma (Company Man)"
    },
    {
        "id": "DOC-004",
        "filename": "IncidentReport_BGH5_2020.pdf",
        "doc_type": "Incident Investigation Report",
        "well_id": "BGH-05",
        "pages": 68,
        "status": "COMPLETED",
        "confidence": 97.1,
        "entities_count": 126,
        "processing_time_s": 55,
        "raw_excerpt": "Gas influx at 3,380m MD in Barail Group. Pit volume gained 22 bbl in 4 min. Well shut in on annular BOP per OISD-STD-174. Wait & Weight kill executed with 12.8 ppg mud.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "R. Gogoi (Safety Supervisor)"
    },
    {
        "id": "DOC-005",
        "filename": "NGT_Katakey_Committee_BGH5_2020.pdf",
        "doc_type": "Regulatory Investigation Report",
        "well_id": "BGH-05",
        "pages": 186,
        "status": "COMPLETED",
        "confidence": 99.2,
        "entities_count": 312,
        "processing_time_s": 145,
        "raw_excerpt": "ROOT CAUSE: Premature removal of BOP before establishing dual mechanical barriers. Single cement plug at ~1,000m in deviated section. Gas column from Lakadong (3,729–3,739m) overcame shallow plug. Well control capability: ZERO at time of kick.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "NGT Justice B.P. Katakey Committee"
    },
    {
        "id": "DOC-006",
        "filename": "WCR_Baghjan_9.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "BGH-09",
        "pages": 198,
        "status": "COMPLETED",
        "confidence": 95.6,
        "entities_count": 284,
        "processing_time_s": 165,
        "raw_excerpt": "Gas kick at 3,380m in lower Barail coal-shale. Pit gain 18 bbl. SPP +140 psi. Wait & Weight kill with 11.2 ppg. Kill verified over 3 circulations.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "R. Gogoi (Safety Supervisor)"
    },
    {
        "id": "DOC-007",
        "filename": "WCR_Naharkatiya_656.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "NHK-656",
        "pages": 278,
        "status": "COMPLETED",
        "confidence": 93.8,
        "entities_count": 445,
        "processing_time_s": 220,
        "raw_excerpt": "Severe borehole breakout in Kopili at 3,780m. Hole enlarged 8.5\" to 14\" (65% enlargement). Narrow MW window 10.15–10.8 ppg. Liner set 3,100m–3,820m.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "S. Das (Geomechanics Lead, Schlumberger)"
    },
    {
        "id": "DOC-008",
        "filename": "GeomechStudy_Baghjan_KumarTalreja_2018.pdf",
        "doc_type": "Geomechanical Study",
        "well_id": "BGH-05",
        "pages": 42,
        "status": "COMPLETED",
        "confidence": 98.8,
        "entities_count": 186,
        "processing_time_s": 35,
        "raw_excerpt": "AAPG #42308: Reducing Drilling Risks in J bend Wells Targeting Basement in Tectonic Area through Geomechanical Solutions. Tipam/Barail MW: 70–73 pcf. Kopili MW: 76–81 pcf at 30° deviation.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "S. Das (Geomechanics Lead, Schlumberger)"
    },
    {
        "id": "DOC-009",
        "filename": "WCR_Rudrasagar_25.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "RDS-25",
        "pages": 265,
        "status": "COMPLETED",
        "confidence": 94.2,
        "entities_count": 356,
        "processing_time_s": 198,
        "raw_excerpt": "Differential sticking at 1,720m in Girujan Clay. String stationary 8 min during equipment malfunction. Overpull 95,000 lbs. Sidetracked with whipstock at 1,680m after 8 days total.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "D. Kalita (Drilling Supt, ONGC Assam)"
    },
    {
        "id": "DOC-010",
        "filename": "WCR_Lakwa_112.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "LK-112",
        "pages": 232,
        "status": "COMPLETED",
        "confidence": 95.0,
        "entities_count": 310,
        "processing_time_s": 175,
        "raw_excerpt": "Gas influx at 3,220m in Barail. Pit gain 12 bbl over 8 min. Background gas from 15 to 220 units. Driller's Method kill with 11.0 ppg.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "M. Baruah (Well Control Specialist, ONGC)"
    },
    {
        "id": "DOC-011",
        "filename": "WCR_Baghjan_21.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "BGH-21",
        "pages": 290,
        "status": "COMPLETED",
        "confidence": 96.4,
        "entities_count": 420,
        "processing_time_s": 210,
        "raw_excerpt": "Kopili overpressure at 3,850m. PP jumped from 63 to 74 pcf (8.42 to 9.9 ppg). Pit gain 15 bbl. MW increased from 10.4 to 12.3 ppg. Liner set at 3,650m.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "P. Saikia (Chief Drilling Eng.)"
    },
    {
        "id": "DOC-012",
        "filename": "WCR_Hugrijan_48.pdf",
        "doc_type": "Well Completion Report",
        "well_id": "HGJ-48",
        "pages": 210,
        "status": "COMPLETED",
        "confidence": 94.5,
        "entities_count": 338,
        "processing_time_s": 185,
        "raw_excerpt": "Progressive seepage losses across Tipam TS-3 to TS-5 (2,450–2,600m). Three LCM pills required. MW reduced from 10.6 to 10.3 ppg.",
        "reviewer_status": "APPROVED",
        "reviewed_by": "B. Borah (Lead Mud Eng., OIL)"
    },
]
